name: Build

on:
  push:
    tags-ignore: 
      - "**"
  workflow_call:
    inputs:
      release_tag:
        required: true
        type: string

jobs:
  build_app:
    runs-on: windows-latest  # For a list of available runner types, refer to
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    env:
      Solution_Name: ClassIsland.sln                       # Replace with your solution name, i.e. MyWpfApp.sln.
      # Test_Project_Path: your-test-project-path                 # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.
      Wap_Project_Directory: ClassIsland/ClassIsland    # Replace with the Wap project directory relative to the solution, i.e. MyWpfApp.Package.
      Wap_Project_Path: ClassIsland/ClassIsland/ClassIsland.csproj                   # Replace with the path to your Wap project, i.e. MyWpf.App.Package\MyWpfApp.Package.wapproj.
      artifact_name: out_app_windows_x64_${{ matrix.trim_assets == 'true' && 'trimmed' || 'full' }}_singleFile
    strategy:
      matrix:
        trim_assets: ['true', 'false']
    name: Build_windows_x64_${{ matrix.trim_assets == 'true' && 'trimmed' || 'full' }}_singleFile
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
          ref: ${{ github.event_name != 'workflow_call' && github.ref || github.event.inputs.release_tag }}
      
      - name: List files
        run: ls
      
      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      
      # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
      
      - name: Build application
        env:
          trim_assets: ${{ matrix.trim_assets }}
        run: |
          ls
          pwsh -ep Bypass -c ./tools/release-gen/publish.ps1 $env:trim_assets

      - name: Upload Unsigned APP to artifacts
        id: upload-unsigned-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact_name }}
          path: ./out/*.zip
          
  build_nupkg:
    runs-on: windows-latest  # For a list of available runner types, refer to
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    env:
      Solution_Name: ClassIsland.sln                       # Replace with your solution name, i.e. MyWpfApp.sln.
      # Test_Project_Path: your-test-project-path                 # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.
      Wap_Project_Directory: ClassIsland/ClassIsland    # Replace with the Wap project directory relative to the solution, i.e. MyWpfApp.Package.
      Wap_Project_Path: ClassIsland/ClassIsland/ClassIsland.csproj                   # Replace with the path to your Wap project, i.e. MyWpf.App.Package\MyWpfApp.Package.wapproj.
    name: Build Nuget Packages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: List files
        run: ls

      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
        
      - name: Build Nuget packages
        env:
          is_release: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          ls
          pwsh -ep Bypass -c ./tools/release-gen/publish-nupkg.ps1 $env:is_release
      
      - name: Upload Nuget packages to GitHub registry
        if: ${{ github.event_name != 'pull_request' }} 
        env:
          GHPKG_KEY: ${{ secrets.GHPKG_KEY }}
        run: |
          dotnet nuget add source --username HelloWRC --password $env:GHPKG_KEY --store-password-in-clear-text --name github "https://nuget.pkg.github.com/ClassIsland/index.json"
          dotnet nuget push .\out\*.nupkg -k $env:GHPKG_KEY --source "github" --skip-duplicate

      - name: Upload Nuget Packages to artifacts
        if: ${{ !matrix.trim_assets }}
        uses: actions/upload-artifact@v4
        with:
          name: out_nupkgs
          path: ./out/*.nupkg
